#! /bin/sh
# postinst script for r-cran-race
#
# see: dh_installdeb(1)

set -e

case "$1" in
  configure)
    if test -x /usr/bin/R; then
      R CMD perl /usr/lib/R/share/perl/build-help.pl --htmllists
    fi
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



exit 0


