#! /bin/sh
# postrm script for r-cran-race

set -e

case "$1" in
  upgrade|remove|purge)
    if test -x /usr/bin/R; then
      R CMD perl /usr/lib/R/share/perl/build-help.pl --htmllists
    fi
    ;;
  failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac



exit 0
