race.init                package:race                R Documentation

_I_n_i_t_i_a_l_i_z_a_t_i_o_n _f_u_n_c_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     This function may be provided by the user for initializing the
     computation of the slave processes. It's definition has to be
     given in the same file in which the functions 'race.wrapper' and
     'race.info' are defined. The name of such file has to be passed as
     first argument to the function 'race'.

_U_s_a_g_e:

     race.init()

_A_r_g_u_m_e_n_t_s:

     The function 'race.init' has to be called with no arguments.

_D_e_t_a_i_l_s:

     This function should be used for initializing the computation on
     each slave, e.g. loading libraries or data needed by
     'race.wrapper', 'race.info', and/or 'race.describe'. The output of
     'race.init' will be passed to these functions.

_V_a_l_u_e:

     The function 'race.init' is expected to return an object of mode
     list.

_A_u_t_h_o_r(_s):

     Mauro Birattari

_S_e_e _A_l_s_o:

     'race', 'race.wrapper', 'race.info', 'race.describe'

_E_x_a_m_p_l_e_s:

     # Please have a look at the function `race.init'
     # defined in the file `example-wrapper.R':
     local({
       source(file.path(system.file(package="race"),
                                "examples","example-wrapper.R"),local=TRUE);
       print(race.init)})

